name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # checkout repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # download dependencies
      - name: build
        run: .\build.bat

      # upload zipped app
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: winX
          path: |
            openssh
            vcxsrv
            help.txt
            winX.bat
